# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Schola POS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Schola POS
  pod 'Stripe'
  pod 'StripeTerminal', '1.0.0'

end
